services:
  db:
    image: postgres:15-alpine
    container_name: biogait-db
    environment:
      POSTGRES_USER: biogait
      POSTGRES_PASSWORD: biogaitsecret
      POSTGRES_DB: biogait
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - biogait-net

  redis:
    image: redis:7-alpine
    container_name: biogait-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - biogait-net

volumes:
  pg_data:
  redis_data:

networks:
  biogait-net:
    driver: bridge